<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Absyn</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" Version="10.0.101"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lib\Lib.csproj" />
    </ItemGroup>

</Project>
